# Workflow derived from https://github.com/ropensci/rix/tree/main/.github/workflows
# and https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-tests-via-nix

permissions:
  contents: read

jobs:
  devtools_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macOS runner commented out to reduce CI time and costs
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Create nix folder to silence warning
        run: mkdir -p ~/.nix-defexpr/channels

      - name: Create .Renviron
        run: |
          echo "GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}" >> ~/.Renviron
        shell: bash

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz

      - uses: cachix/cachix-action@v14
        with:
          name: rstats-on-nix

      - name: Build development environment
        run: nix-shell default.nix --quiet --pure --run "Rscript -e \"sessionInfo()\""

      - name: Run devtools::test() via nix-shell
        run: nix-shell default.nix --quiet --pure --run "Rscript -e \"devtools::test(stop_on_failure = TRUE)\""
